export enum AuthConstants {
  // login
  POST_LOGIN_REQUEST = 'POST/LOGIN/REQUEST',
  POST_LOGIN_SUCCESS = 'POST/LOGIN/SUCCESS',
  POST_LOGIN_FAILURE = 'POST/LOGIN/FAILURE',
  // logout
  POST_LOGOUT_REQUEST = 'POST/LOGOUT/REQUEST',
  POST_LOGOUT_SUCCESS = 'POST/LOGOUT/SUCCESS',
  POST_LOGOUT_FAILURE = 'POST/LOGOUT/FAILURE',
}
