export enum UsersConstants {
  // register
  POST_USERS_REQUEST = '/POST/USERS/REQUEST',
  POST_USERS_SUCCESS = '/POST/USERS/SUCCESS',
  POST_USERS_FAILURE = '/POST/USERS/FAILURE',
  // retrieve
  GET_USERS_REQUEST = '/GET/USERS/REQUEST',
  GET_USERS_SUCCESS = '/GET/USERS/SUCCESS',
  GET_USERS_FAILURE = '/GET/USERS/FAILURE',
  // update
  PUT_USERS_REQUEST = '/PUT/USERS/REQUEST',
  PUT_USERS_SUCCESS = '/PUT/USERS/SUCCESS',
  PUT_USERS_FAILURE = '/PUT/USERS/FAILURE',
  // reset state
  RESET_USER_STATE = 'RESET/USER/STATE',
  // update password
  PUT_USER_UPDATE_PASSWORD_REQUEST = 'PUT/USER/UPDATE/PASSWORD/REQUEST',
  PUT_USER_UPDATE_PASSWORD_SUCCESS = 'PUT/USER/UPDATE/PASSWORD/SUCCESS',
  PUT_USER_UPDATE_PASSWORD_FAILURE = 'PUT/USER/UPDATE/PASSWORD/FAILURE',
  PUT_USER_UPDATE_PASSWORD_RESET = 'PUT/USER/UPDATE/PASSWORD/RESET',
  // reset errors
  RESET_ERRORS = 'RESET/ERRORS',
  // recovery password
  POST_USER_RECOVERY_PASSWORD_REQUEST = 'POST/USER/RECOVERY/PASSWORD/REQUEST',
  POST_USER_RECOVERY_PASSWORD_SUCCESS = 'POST/USER/RECOVERY/PASSWORD/SUCCESS',
  POST_USER_RECOVERY_PASSWORD_FAILURE = 'POST/USER/RECOVERY/PASSWORD/FAILURE',
}
