export * from './IRol';
export * from './IUser';
export * from './IPetSex';
export * from './IPatient';
export * from './IAppointment';
export * from './ITests';
export * from './IOwner';
export * from './IRecoveryPassword';
export * from './IRecord';
